name: Test

on: [push]

jobs:
  tests:
    name: Test
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Configure Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install package
        run: |
          pip install -e .

      - name: Run tests
        run: |
          pip install pytest
          pytest test_mojimoji.py --junitxml=junit/test-results-${{ matrix.python_version }}.xml

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results-${{ matrix.python_version }}
          path: junit/test-results-${{ matrix.python_version }}.xml
        if: ${{ always() }}
